from django.utils.translation import ugettext as _


general_category = [
    (_('General'), _('General')),
    (_('Music'), _('Music')),
    (_('Personal'),_('Personal')),
    (_('Fanny'), _('Fanny')),
    (_('Sport'), _('Sport')),
    (_('Religion'), _('Religion')),
    (_('Science'), _('Science')),
    (_('Medical'), _('Medical')),
    (_('Engineering'), _('Engineering')),
    (_('Physics'), _('Physics')),
    (_('Programming'), _('Programming')),
    (_('Networking'), _('Networking')),
    (_('Medical'), _('Medical')),
    (_('Chemistry'), _('Chemistry')),
    (_('Mathematics'), _('Mathematics')),
    (_('Information Technology'), _('Information Technology')),
    (_('Education'), _('Education')),
    (_('Others'), _('Others')),
]

# first in admin panel appear, second appear to user
book_category = [
    (_('General'), _('General')),
    (_('Medical'), _('Medical')),
    (_('Anatomy'), _('Anatomy')),
    (_('Anesthesiology'), _('Anesthesiology')),
    (_('Biology'), _('Biology')),
    (_('Cardiology'), _('Cardiology')),
    (_('Community'), _('Community')),
    (_('Dermatology'), _('Dermatology')),
    (_('ENT'), _('ENT')),
    (_('Hematology'), _('Hematology')),
    (_('Histology'), _('Histology')),
    (_('Medicine'), _('Medicine')),
    (_('Microbiology'), _('Microbiology')),
    (_('Neurology'), _('Neurology')),
    (_('Gynecology'), _('Gynecology')),
    (_('Obstetrics'), _('Obstetrics')),
    (_('Oncology'), _('Oncology')),
    (_('Ophthalmology'), _('Ophthalmology')),
    (_('Parasitology'), _('Parasitology')),
    (_('Pathology'), _('Pathology')),
    (_('Pediatrics'), _('Pediatrics')),
    (_('Pharmacology'), _('Pharmacology')),
    (_('Physiology'), _('Physiology')),
    (_('Psychology'), _('Psychology')),
    (_('Radiology'), _('Radiology')),
    (_('Others'), _('Others')),
]

# first in admin panel appear, second appear to user
material_list = [
    (_('General'), _('General')),
    (_('Anatomy'), _('Anatomy')),
    (_('Anesthesiology'), _('Anesthesiology')),
    (_('Biology'), _('Biology')),
    (_('Cardiology'), _('Cardiology')),
    (_('Community'), _('Community')),
    (_('Dermatology'), _('Dermatology')),
    (_('ENT'), _('ENT')),
    (_('Hematology'), _('Hematology')),
    (_('Histology'), _('Histology')),
    (_('Medicine'), _('Medicine')),
    (_('Microbiology'), _('Microbiology')),
    (_('Neurology'), _('Neurology')),
    (_('Gynecology'), _('Gynecology')),
    (_('Obstetrics'), _('Obstetrics')),
    (_('Oncology'), _('Oncology')),
    (_('Ophthalmology'), _('Ophthalmology')),
    (_('Parasitology'), _('Parasitology')),
    (_('Pathology'), _('Pathology')),
    (_('Pediatrics'), _('Pediatrics')),
    (_('Pharmacology'), _('Pharmacology')),
    (_('Physiology'), _('Physiology')),
    (_('Psychology'), _('Psychology')),
    (_('Radiology'), _('Radiology')),
    (_('Surgery'), _('Surgery')),
    (_('Others'), _('Others')),
]
